version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "logParser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1irjfdliri3ct"
s3_prefix = "logParser"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

